const PROJECTS = [
  {
    title: "Expert impôts — Social media videos",
    tags: ["Social", "3D"],
    tools: "Blender / AE",
    year: "2026",
    role: "3D Animation, Compositing",
    client: "Expert impôts",
    application: "Social / 9:16",
    desc: "Social media video content — 3D animations and compositing designed for vertical social placement.",
    desc_fr: "Contenus vidéo pour les réseaux sociaux — animations 3D et compositing conçus pour un format social vertical.",
    hero: "vega_drop_hero.mp4",
    stills: ["scene_01_still.png", "scene_02_still.png"]
  },
  {
    title: "Kanopée associés — Explainer videos and edits",
    tags: ["Explainer", "Edit"],
    tools: "After Effects",
    year: "2026",
    role: "Motion Design, Edit",
    client: "Kanopée associés",
    application: "Broadcast / Explainer",
    desc: "Explainer videos and editorial edits — clear, fast-paced motion graphics designed to communicate key messages effectively.",
    desc_fr: "Vidéos explicatives et montages éditoriaux — motion graphics clairs et dynamiques conçus pour communiquer efficacement les messages clés.",
    hero: "boredraw_hero.mp4",
    stills: ["boredraw_ui_01.png", "boredraw_ui_02.png"]
  },
  {
    title: "Holovisio — Characters creation and animations",
    tags: ["2D", "3D"],
    tools: "After Effects",
    year: "2025",
    role: "Motion Design",
    client: "Holovisio",
    application: "Product / UI Motion",
    desc: "Character creation and animation — designing and animating original characters for product and brand storytelling.",
    desc_fr: "Création et animation de personnages — conception et animation de personnages originaux pour le storytelling produit et marque.",
    hero: "cashout_hero.mp4",
    stills: ["cashout_states.png"]
  },
  {
    title: "Holovisio — STEP files animations",
    tags: ["3D"],
    tools: "Unreal Engine 5",
    year: "2026",
    role: "3D Animation",
    client: "Holovisio",
    application: "Product / Technical",
    desc: "Technical STEP file animations — bringing CAD models to life with dynamic 3D animation for product visualization.",
    desc_fr: "Animations de fichiers STEP techniques — mise en mouvement de modèles CAO avec des animations 3D dynamiques pour la visualisation produit.",
    hero: "roulette_ue5_hero.mp4",
    stills: ["roulette_table.png", "roulette_niagara.png"]
  },
  {
    title: "Yeman — Wish card",
    tags: ["3D"],
    tools: "Blender",
    year: "2025",
    role: "3D Animation",
    client: "Yeman",
    application: "Product Film / Loop",
    desc: "An animated wish card — a crafted 3D animation designed for a polished, looping product film.",
    desc_fr: "Une carte de vœux animée — une animation 3D soignée conçue pour un film produit en boucle.",
    hero: "phone_orbit_hero.mp4",
    stills: ["phone_orbit_still.png"]
  },
  {
    title: "Recognity - SAMDOC — 3D animation",
    tags: ["3D", "Explainer"],
    tools: "After Effects / Blender",
    year: "2025",
    role: "Motion Design, 3D",
    client: "Recognity - SAMDOC",
    application: "Product / Explainer",
    desc: "3D animation for SAMDOC — product-focused motion design combining After Effects and Blender for clear visual storytelling.",
    desc_fr: "Animation 3D pour SAMDOC — motion design orienté produit combinant After Effects et Blender pour un storytelling visuel clair.",
    hero: "1up_hero.mp4",
    stills: ["1up_still_01.png"]
  }
];

const I18N = {
  en: {
    "nav.work": "Work",
    "nav.about": "About",
    "nav.contact": "Contact",
    "hero.eyebrow": "Motion Designer — Open to work",
    "hero.sub": "Guillaume — building broadcast graphics, 3D product animation, and real-time interactive experiences. 5+ years freelance, currently exploring UE5 for live, data-driven motion.",
    "hero.tools": "Tools",
    "hero.tools.val": "After Effects, Blender, UE5",
    "hero.focus": "Focus",
    "hero.focus.val": "Broadcast · Betting · Real-time",
    "hero.based": "Based",
    "hero.based.val": "Paris, France",
    "scroll": "SCROLL",
    "work.label": "Selected Work",
    "filter.all": "All",
    "clients.label": "Clients",
    "about.label": "About",
    "about.h2": "Motion that has to <span class=\"accent\">read instantly</span> — and still feel considered.",
    "about.p": "I'm a 2D/3D motion designer and creative technologist based in Paris, with over 5 years creating animated content for brands, products, and digital platforms — explainer videos, marketing animations, event teasers, and social content. An engineering background in image processing means I work equally comfortably on the technical side: dynamic After Effects pipelines, real-time UE5 builds, and motion integrated directly into UI/UX. I like the constraint of work that has to land in three seconds, and the craft of making it still feel deliberate.",
    "contact.label": "Contact",
    "contact.h2": "Got a project in mind?",
    "contact.p": "Currently available for freelance and full-time motion design roles, with particular interest in real-time / UE5 work. Also reachable at +33 6 37 30 03 18.",
    "footer.hours": "Hours",
    "footer.hours.val": "Mon — Fri",
    "footer.follow": "Follow",
    "footer.role": "Motion Design",
    "cs.close": "CLOSE",
    "cs.next.label": "Next project",
    "cs.client": "Client",
    "cs.role": "Role",
    "cs.tools": "Tools",
    "cs.year": "Year",
    "tile.view": "View",
    "cv.label": "CV",
    "cv.download": "Download CV"
  },
  fr: {
    "nav.work": "Projets",
    "nav.about": "À propos",
    "nav.contact": "Contact",
    "hero.eyebrow": "Motion Designer — Disponible",
    "hero.sub": "Guillaume — création de contenus broadcast, animation 3D produit et expériences interactives en temps réel. 5+ ans en freelance, actuellement en exploration UE5 pour du motion data-driven en temps réel.",
    "hero.tools": "Outils",
    "hero.tools.val": "After Effects, Blender, UE5",
    "hero.focus": "Domaines",
    "hero.focus.val": "Broadcast · Betting · Temps réel",
    "hero.based": "Basé à",
    "hero.based.val": "Paris, France",
    "scroll": "DÉFILER",
    "work.label": "Projets sélectionnés",
    "filter.all": "Tous",
    "clients.label": "Clients",
    "about.label": "À propos",
    "about.h2": "Du motion qui doit <span class=\"accent\">se lire instantanément</span> — tout en restant soigné.",
    "about.p": "Motion designer 2D/3D et creative technologist basé à Paris, avec plus de 5 ans d'expérience dans la création de contenus animés pour des marques, produits et plateformes digitales — vidéos explicatives, animations marketing, teasers événementiels et contenus sociaux. Une formation d'ingénieur en traitement de l'image me permet de travailler aussi bien sur le volet technique : pipelines After Effects dynamiques, builds UE5 en temps réel, et motion intégré directement en UI/UX. J'aime la contrainte du travail qui doit fonctionner en trois secondes, et le soin de le rendre quand même intentionnel.",
    "contact.label": "Contact",
    "contact.h2": "Un projet en tête ?",
    "contact.p": "Actuellement disponible pour des missions freelance et des postes en motion design, avec un intérêt particulier pour le temps réel / UE5. Aussi joignable au +33 6 37 30 03 18.",
    "footer.hours": "Horaires",
    "footer.hours.val": "Lun — Ven",
    "footer.follow": "Suivre",
    "footer.role": "Motion Design",
    "cs.close": "FERMER",
    "cs.next.label": "Projet suivant",
    "cs.client": "Client",
    "cs.role": "Rôle",
    "cs.tools": "Outils",
    "cs.year": "Année",
    "tile.view": "Voir",
    "cv.label": "CV",
    "cv.download": "Télécharger le CV"
  }
};
