const PROJECTS = [
  {
    title: "AC Consulting",
    tags: ["Social"],
    tools: "After Effects / Cinema 4D",
    year: "2023",
    role: "Storyboard, Asset Creation, Animation, Simulations",
    client: "AC Consulting",
    application: "Corporate",
    desc: "Motion design for AC Consulting — storyboard, asset creation, animation, and simulations for a brand collaboration reveal, made with After Effects and Cinema 4D.",
    desc_fr: "Motion design pour AC Consulting — storyboard, création d'assets, animation et simulations pour une révélation de collaboration de marque, réalisée avec After Effects et Cinema 4D.",
    hero: "AC_Consulting/Animation.mp4",
    stills: ["AC_Consulting/ac_reveal.gif"]
  },
  {
    title: "Expert impôts — Social media videos",
    tags: ["Social", "3D"],
    tools: "After Effects / Cinema 4D",
    year: "2026",
    role: "Storyboard, Asset Creation, Animation, Simulations",
    client: "Expert impôts",
    application: "Social / 9:16",
    desc: "Social media video content for Expert Impôts — storyboard, asset creation, animation, and simulations designed for vertical social placement, made with After Effects and Cinema 4D.",
    desc_fr: "Contenus vidéo pour les réseaux sociaux d'Expert Impôts — storyboard, création d'assets, animation et simulations conçus pour un format social vertical, réalisés avec After Effects et Cinema 4D.",
    hero: "Expert_impots/expert_impots.mp4",
    stills: ["Expert_impots/Format_4_5.mp4", "Expert_impots/expert_invest.gif", "Expert_impots/expert_eval.gif", "Expert_impots/expert_save.gif"]
  },
  {
    title: "Fortel",
    tags: ["2D"],
    tools: "After Effects / Cinema 4D",
    year: "2025",
    role: "Storyboard, Asset Creation, Animation, Simulations",
    client: "Fortel",
    application: "Corporate / Greeting card",
    desc: "Animated New Year's greeting card for Fortel — storyboard, asset creation, animation, and simulations for a celebratory map-based animation highlighting the company's multiple office locations, made with After Effects and Cinema 4D.",
    desc_fr: "Carte de vœux animée pour Fortel — storyboard, création d'assets, animation et simulations pour une animation festive basée sur une carte, mettant en avant les différents sites de l'entreprise, réalisée avec After Effects et Cinema 4D.",
    hero: "Fortel/Fortel.mp4",
    stills: ["Fortel/fortel_map.gif", "Fortel/fortel_greeting.gif"]
  },
  {
    title: "Holovisio — Characters creation and animations",
    tags: ["2D", "3D"],
    tools: "After Effects / Cinema 4D",
    year: "2025",
    role: "Storyboard, Asset Creation, Animation, Simulations",
    client: "Holovisio",
    application: "Product / UI Motion",
    desc: "Character creation and animation — storyboard, asset creation, animation, and simulations for original characters designed for product and brand storytelling, made with After Effects and Cinema 4D.",
    desc_fr: "Création et animation de personnages — storyboard, création d'assets, animation et simulations pour des personnages originaux conçus pour le storytelling produit et marque, réalisés avec After Effects et Cinema 4D.",
    hero: "Holovisio/Characters/To_send_Animation_finale_black.mp4",
    heroStart: 2,
    heroPosition: "top",
    stills: ["Holovisio/Characters/Render_JPS_1.mp4", "Holovisio/Characters/Simone.mp4", "Holovisio/Characters/holo_gesture.gif", "Holovisio/Characters/holo_talk.gif"]
  },
  {
    title: "Holovisio — STEP files animations",
    tags: ["3D"],
    tools: "After Effects / Cinema 4D",
    year: "2026",
    role: "3D Animation",
    client: "Holovisio",
    application: "Product / Technical",
    desc: "Technical STEP file animations — bringing CAD models to life with dynamic 3D animation for product visualization.",
    desc_fr: "Animations de fichiers STEP techniques — mise en mouvement de modèles CAO avec des animations 3D dynamiques pour la visualisation produit.",
    hero: "Holovisio/CAD/Animation_orano_v4.mp4",
    stills: ["Holovisio/CAD/cad_drive.gif", "Holovisio/CAD/cad_radar.gif"]
  },
  {
    title: "Kanopée associés — Explainer videos and edits",
    tags: ["Explainer", "Edit"],
    tools: "After Effects / Cinema 4D",
    year: "2026",
    role: "Storyboard, Asset Creation, Animation, Simulations, Edit",
    client: "Kanopée associés",
    application: "Broadcast / Explainer",
    desc: "Explainer videos and editorial edits — storyboard, asset creation, animation, and simulations combined with editorial edits, made with After Effects and Cinema 4D.",
    desc_fr: "Vidéos explicatives et montages éditoriaux — storyboard, création d'assets, animation et simulations combinés à des montages éditoriaux, réalisés avec After Effects et Cinema 4D.",
    hero: "Kanopée associés/Motion_Collectif_1310_Main.mp4",
    stills: ["Kanopée associés/Link20Avril.mp4", "Kanopée associés/kanopee_stat.gif", "Kanopée associés/kanopee_wipe.gif"]
  },
  {
    title: "Laodis",
    tags: ["3D"],
    tools: "After Effects / Cinema 4D",
    year: "2022",
    role: "Storyboard, Asset Creation, Animation, Simulations",
    client: "Laodis",
    application: "Product",
    desc: "3D product animation for Laodis — storyboard, asset creation, animation, and simulations, made with After Effects and Cinema 4D.",
    desc_fr: "Animation 3D produit pour Laodis — storyboard, création d'assets, animation et simulations, réalisée avec After Effects et Cinema 4D.",
    hero: "Laodis/laodis_2.mp4",
    stills: ["Laodis/laodis_1.mp4", "Laodis/laodis_multi.gif"]
  },
  {
    title: "Recognity - SAMDOC — 3D animation",
    tags: ["3D", "Explainer"],
    tools: "After Effects / Cinema 4D",
    year: "2023",
    role: "Asset Creation, Animation, Simulations",
    client: "Recognity - SAMDOC",
    application: "Product / Explainer",
    desc: "3D animation for SAMDOC, made in collaboration with two other artists who handled the screenplay and storyboard — I built the assets, animation, and simulations from their shot ideas, using After Effects and Cinema 4D.",
    desc_fr: "Animation 3D pour SAMDOC, réalisée en collaboration avec deux autres artistes en charge du scénario et du storyboard — j'ai créé les assets, l'animation et les simulations à partir de leurs idées de plans, avec After Effects et Cinema 4D.",
    hero: "Samdoc/samdoc.mp4",
    stills: ["Samdoc/samdoc_pod.gif", "Samdoc/samdoc_bins.gif", "Samdoc/samdoc_logo.gif"]
  }
];

const I18N = {
  en: {
    "nav.work": "Work",
    "nav.about": "About",
    "nav.contact": "Contact",
    "hero.eyebrow": "Motion Designer — Open to work",
    "hero.sub": "Guillaume — building broadcast graphics, 3D product animation, and real-time interactive experiences. 5+ years freelance, currently exploring UE5 for live, data-driven motion.",
    "hero.tools": "Tools",
    "hero.tools.val": "After Effects, Blender, UE5",
    "hero.focus": "Focus",
    "hero.focus.val": "Social Media · CAD Animations · Explainers · Character Animations · Logo & Kinetic Typography · Product Visualization · UI/UX Motion · Event & Advertising",
    "hero.based": "Based",
    "hero.based.val": "Paris, France",
    "scroll": "SCROLL",
    "work.label": "Selected Work",
    "filter.all": "All",
    "clients.label": "Clients",
    "about.label": "About",
    "about.h2": "Motion that has to <span class=\"accent\">read instantly</span> — and still feel considered.",
    "about.p": "2D/3D Motion Designer with over 5 years of experience creating animated content for brands, products, and digital platforms. Passionate about combining design and technology to produce engaging visual storytelling. Experienced in producing explainer animations, marketing videos, event teasers, and social media content. With a strong technical background in both motion design and software development, delivering efficient production workflows and technically advanced visuals across every project.",
    "contact.label": "Contact",
    "contact.h2": "Got a project in mind?",
    "contact.p": "Currently available for freelance and full-time motion design roles.",
    "footer.hours": "Hours",
    "footer.hours.val": "Mon — Fri",
    "footer.follow": "Follow",
    "footer.role": "Motion Design",
    "cs.close": "CLOSE",
    "cs.next.label": "Next project",
    "cs.client": "Client",
    "cs.role": "Role",
    "cs.tools": "Tools",
    "cs.year": "Year",
    "tile.view": "View",
    "cv.label": "CV",
    "nav.playground": "Playground",
    "playground.label": "Playground",
    "playground.intro": "Personal experiments, creative coding, and interactive projects. Coming soon.",
    "cv.download": "Download CV"
  },
  fr: {
    "nav.work": "Projets",
    "nav.about": "À propos",
    "nav.contact": "Contact",
    "hero.eyebrow": "Motion Designer — Disponible",
    "hero.sub": "Guillaume — création de contenus broadcast, animation 3D produit et expériences interactives en temps réel. 5+ ans en freelance, actuellement en exploration UE5 pour du motion data-driven en temps réel.",
    "hero.tools": "Outils",
    "hero.tools.val": "After Effects, Blender, UE5",
    "hero.focus": "Domaines",
    "hero.focus.val": "Réseaux sociaux · Animations CAO · Explainers · Animations de personnages · Logo & Typographie cinétique · Visualisation produit · Motion UI/UX · Événementiel & Publicité",
    "hero.based": "Basé à",
    "hero.based.val": "Paris, France",
    "scroll": "DÉFILER",
    "work.label": "Projets sélectionnés",
    "filter.all": "Tous",
    "clients.label": "Clients",
    "about.label": "À propos",
    "about.h2": "Du motion qui doit <span class=\"accent\">se lire instantanément</span> — tout en restant soigné.",
    "about.p": "Motion Designer 2D/3D avec plus de 5 ans d'expérience dans la création de contenus animés pour des marques, des produits et des plateformes digitales. Passionné par l'alliance du design et de la technologie pour produire un storytelling visuel engageant. Expérimenté dans la production d'animations explicatives, de vidéos marketing, de teasers événementiels et de contenus pour les réseaux sociaux. Avec une solide formation technique en motion design et développement logiciel, garantissant des workflows de production efficaces et des visuels techniquement avancés sur chaque projet.",
    "contact.label": "Contact",
    "contact.h2": "Un projet en tête ?",
    "contact.p": "Actuellement disponible pour des missions freelance et des postes en motion design.",
    "footer.hours": "Horaires",
    "footer.hours.val": "Lun — Ven",
    "footer.follow": "Suivre",
    "footer.role": "Motion Design",
    "cs.close": "FERMER",
    "cs.next.label": "Projet suivant",
    "cs.client": "Client",
    "cs.role": "Rôle",
    "cs.tools": "Outils",
    "cs.year": "Année",
    "tile.view": "Voir",
    "cv.label": "CV",
    "nav.playground": "Playground",
    "playground.label": "Playground",
    "playground.intro": "Expériences personnelles, creative coding et projets interactifs. Bientôt disponible.",
    "cv.download": "Télécharger le CV"
  }
};
