const PROJECTS = [
  {
    title: "Expert impôts — Social media videos",
    tags: ["Social", "3D"],
    tools: "Blender / AE",
    year: "2026",
    role: "3D Animation, Compositing",
    client: "Expert impôts",
    application: "Social / 9:16",
    desc: "Social media video content — 3D animations and compositing designed for vertical social placement.",
    desc_fr: "Contenus vidéo pour les réseaux sociaux — animations 3D et compositing conçus pour un format social vertical.",
    hero: "vega_drop_hero.mp4",
    stills: ["scene_01_still.png", "scene_02_still.png"]
  },
  {
    title: "Kanopée associés — Explainer videos and edits",
    tags: ["Explainer", "Edit"],
    tools: "After Effects",
    year: "2026",
    role: "Motion Design, Edit",
    client: "Kanopée associés",
    application: "Broadcast / Explainer",
    desc: "Explainer videos and editorial edits — clear, fast-paced motion graphics designed to communicate key messages effectively.",
    desc_fr: "Vidéos explicatives et montages éditoriaux — motion graphics clairs et dynamiques conçus pour communiquer efficacement les messages clés.",
    hero: "boredraw_hero.mp4",
    stills: ["boredraw_ui_01.png", "boredraw_ui_02.png"]
  },
  {
    title: "Holovisio — Characters creation and animations",
    tags: ["2D", "3D"],
    tools: "After Effects",
    year: "2025",
    role: "Motion Design",
    client: "Holovisio",
    application: "Product / UI Motion",
    desc: "Character creation and animation — designing and animating original characters for product and brand storytelling.",
    desc_fr: "Création et animation de personnages — conception et animation de personnages originaux pour le storytelling produit et marque.",
    hero: "cashout_hero.mp4",
    stills: ["cashout_states.png"]
  },
  {
    title: "Holovisio — STEP files animations",
    tags: ["3D"],
    tools: "Unreal Engine 5",
    year: "2026",
    role: "3D Animation",
    client: "Holovisio",
    application: "Product / Technical",
    desc: "Technical STEP file animations — bringing CAD models to life with dynamic 3D animation for product visualization.",
    desc_fr: "Animations de fichiers STEP techniques — mise en mouvement de modèles CAO avec des animations 3D dynamiques pour la visualisation produit.",
    hero: "roulette_ue5_hero.mp4",
    stills: ["roulette_table.png", "roulette_niagara.png"]
  },
  {
    title: "Yeman — Wish card",
    tags: ["3D"],
    tools: "Blender",
    year: "2025",
    role: "3D Animation",
    client: "Yeman",
    application: "Product Film / Loop",
    desc: "An animated wish card — a crafted 3D animation designed for a polished, looping product film.",
    desc_fr: "Une carte de vœux animée — une animation 3D soignée conçue pour un film produit en boucle.",
    hero: "phone_orbit_hero.mp4",
    stills: ["phone_orbit_still.png"]
  },
  {
    title: "Recognity - SAMDOC — 3D animation",
    tags: ["3D", "Explainer"],
    tools: "After Effects / Blender",
    year: "2025",
    role: "Motion Design, 3D",
    client: "Recognity - SAMDOC",
    application: "Product / Explainer",
    desc: "3D animation for SAMDOC — product-focused motion design combining After Effects and Blender for clear visual storytelling.",
    desc_fr: "Animation 3D pour SAMDOC — motion design orienté produit combinant After Effects et Blender pour un storytelling visuel clair.",
    hero: "1up_hero.mp4",
    stills: ["1up_still_01.png"]
  }
];

const I18N = {
  en: {
    "nav.work": "Work",
    "nav.about": "About",
    "nav.contact": "Contact",
    "hero.eyebrow": "Motion Designer — Open to work",
    "hero.sub": "Guillaume — building broadcast graphics, 3D product animation, and real-time interactive experiences. 5+ years freelance, currently exploring UE5 for live, data-driven motion.",
    "hero.tools": "Tools",
    "hero.tools.val": "After Effects, Blender, UE5",
    "hero.focus": "Focus",
    "hero.focus.val": "Social Media · CAD Animations · Explainers · Character Animations · Logo & Kinetic Typography · Product Visualization · UI/UX Motion · Event & Advertising",
    "hero.based": "Based",
    "hero.based.val": "Paris, France",
    "scroll": "SCROLL",
    "work.label": "Selected Work",
    "filter.all": "All",
    "clients.label": "Clients",
    "about.label": "About",
    "about.h2": "Motion that has to <span class=\"accent\">read instantly</span> — and still feel considered.",
    "about.p": "2D/3D Motion Designer with over 5 years of experience creating animated content for brands, products, and digital platforms. Passionate about combining design and technology to produce engaging visual storytelling. Experienced in producing explainer animations, marketing videos, event teasers, and social media content. With a strong technical background in both motion design and software development, delivering efficient production workflows and technically advanced visuals across every project.",
    "contact.label": "Contact",
    "contact.h2": "Got a project in mind?",
    "contact.p": "Currently available for freelance and full-time motion design roles.",
    "footer.hours": "Hours",
    "footer.hours.val": "Mon — Fri",
    "footer.follow": "Follow",
    "footer.role": "Motion Design",
    "cs.close": "CLOSE",
    "cs.next.label": "Next project",
    "cs.client": "Client",
    "cs.role": "Role",
    "cs.tools": "Tools",
    "cs.year": "Year",
    "tile.view": "View",
    "cv.label": "CV",
    "nav.playground": "Playground",
    "playground.label": "Playground",
    "playground.intro": "Personal experiments, creative coding, and interactive projects. Coming soon.",
    "cv.download": "Download CV"
  },
  fr: {
    "nav.work": "Projets",
    "nav.about": "À propos",
    "nav.contact": "Contact",
    "hero.eyebrow": "Motion Designer — Disponible",
    "hero.sub": "Guillaume — création de contenus broadcast, animation 3D produit et expériences interactives en temps réel. 5+ ans en freelance, actuellement en exploration UE5 pour du motion data-driven en temps réel.",
    "hero.tools": "Outils",
    "hero.tools.val": "After Effects, Blender, UE5",
    "hero.focus": "Domaines",
    "hero.focus.val": "Réseaux sociaux · Animations CAO · Explainers · Animations de personnages · Logo & Typographie cinétique · Visualisation produit · Motion UI/UX · Événementiel & Publicité",
    "hero.based": "Basé à",
    "hero.based.val": "Paris, France",
    "scroll": "DÉFILER",
    "work.label": "Projets sélectionnés",
    "filter.all": "Tous",
    "clients.label": "Clients",
    "about.label": "À propos",
    "about.h2": "Du motion qui doit <span class=\"accent\">se lire instantanément</span> — tout en restant soigné.",
    "about.p": "Motion Designer 2D/3D avec plus de 5 ans d'expérience dans la création de contenus animés pour des marques, des produits et des plateformes digitales. Passionné par l'alliance du design et de la technologie pour produire un storytelling visuel engageant. Expérimenté dans la production d'animations explicatives, de vidéos marketing, de teasers événementiels et de contenus pour les réseaux sociaux. Avec une solide formation technique en motion design et développement logiciel, garantissant des workflows de production efficaces et des visuels techniquement avancés sur chaque projet.",
    "contact.label": "Contact",
    "contact.h2": "Un projet en tête ?",
    "contact.p": "Actuellement disponible pour des missions freelance et des postes en motion design.",
    "footer.hours": "Horaires",
    "footer.hours.val": "Lun — Ven",
    "footer.follow": "Suivre",
    "footer.role": "Motion Design",
    "cs.close": "FERMER",
    "cs.next.label": "Projet suivant",
    "cs.client": "Client",
    "cs.role": "Rôle",
    "cs.tools": "Outils",
    "cs.year": "Année",
    "tile.view": "Voir",
    "cv.label": "CV",
    "nav.playground": "Playground",
    "playground.label": "Playground",
    "playground.intro": "Expériences personnelles, creative coding et projets interactifs. Bientôt disponible.",
    "cv.download": "Télécharger le CV"
  }
};
